title: "Henri BRUVRY"
subtitle: "Pâtisserie à l'assiette, Gastronomie"
responsable: "Henri BRUVRY"
adresse: "36, Boulevard François Mitterrand"
codepostal: "62930"
ville: Wimereux
telephone: "+33 7 71 66 98 51"
email: "henri.bruvry@outlook.fr"
facebook: Henri BRUVRY
linkfacebook: "www.facebook.com/henribruvry"
hebergeur: "onRender.com"
realisation: "DB_Design"